config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get "pokemons/inventory", to: "pokemons#inventory", as: "inventory"
  patch "pokemons/:id/reactivate", to: "pokemons#reactivate", as: "reactivate"
  patch "pokemons/:id/deactivate", to: "pokemons#deactivate", as: "deactivate"
  resources :pokemons do
    resources :bookings, except: %i[edit update]
  end
  resources :bookings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
  end
end

app/models/booking.rb
require_relative '../validators/availability_validator.rb'
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_one :review

  validates :start_dt, :end_dt, presence: true
  validates :range, presence: true, availability: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_dt.blank? || start_dt.blank?

    if end_dt < start_dt
      errors.add(:end_dt, "must be after the start date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]

  def index
    @pokemons = Pokemon.all
    @user = current_user
    @bookings = policy_scope(Booking).order(end_dt: :desc)
    @review = Review.new
  end

  def show
  end

  def update
  end

  def new
    @pokemon = Pokemon.find(params[:pokemon_id])
    @booking = Booking.new
    authorize @booking
    @bookings = Booking.all
  end

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.pokemon_id = params[:pokemon_id]
    @booking.user_id = current_user[:id]
    @booking.price_paid = ((@booking.end_dt - @booking.start_dt) * @pokemon.price_per_day)
    @booking.range = (@booking.start_dt..@booking.end_dt)
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to pokemon_path(@pokemon)
      flash[:failure] = "Dates unavailable"
    end
  end

  def destroy
    if @booking.start_dt < Time.now
      redirect_to bookings_path
      flash[:failure] = "Cannot cancel booking after #{@booking.start_dt}."
    elsif @booking.start_dt < Date.yesterday
      redirect_to bookings_path
      flash[:failure] = "Cannot cancel booking with less than 24 hours notice."
    else
      @booking.destroy
      flash[:success] = "Deleted booking."
      redirect_to bookings_path
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_dt, :end_dt)
  end

  # def booking_status
  #   if @booking.start_dt < Time.now
  #     redirect_to bookings_path
  #     flash[:failure] = "#{@booking.start_dt} has already passed"
  #   end
  # end

  # def booking_state
  #    if (Time.now > booking.end_dt && !booking.rating)
  #     return "<span class="ml-3 mb-2 badge badge-pill badge-info">= link_to "Leave review!", new_booking_review_path(booking.id) </span>"

  #   # <!-- If booking start date is still upcoming => show upcoming label and 'cancel button' -->
  #    elsif (Time.now < booking.start_dt )
  #     <span class="badge badge-pill badge-warning"> Upcoming!</span>
  #     = link_to 'Cancel', booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:'ml-3 mb-2 badge badge-pill badge-danger'

  #   # <!-- If booking has left a review => show review score -->
  #    elsif (booking.rating)
  #     <span class="stars badge badge-pill">Your rating:
  #        booking.rating.times do
  #         <i class='fas fa-star'></i>
  #        end
  #        (5 - booking.rating).times do
  #         <i class='far fa-star'></i>
  #        end
  #     </span>

  #   # <!-- If Time.now is after start date and before end date => show current label -->
  #    elsif (Time.now > booking.start_dt && Time.now < booking.end_dt)
  #     <span class="badge badge-pill badge-secondary">Ongoing!</span>

  #    end
  # end
end

app/views/bookings/_new.html.erb
<%= simple_form_for [@pokemon, @booking] do |f| %>

  <% if @booking.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div id='pokemon-booking-dates' data-unavailable="<%= @pokemon.unavailable_dates.to_json %>">
  <%= simple_form_for([@pokemon, @booking]) do |f| %>
  <%= f.input :start_dt, as: :string, label: "Dates", placeholder: "From", wrapper_html: { class: "inline_field_wrapper" } %>
  <%= f.input :end_dt, as: :string, label: '&nbsp;'.html_safe, placeholder: "To", disabled: true, wrapper_html: { class: "inline_field_wrapper" } %>
  <p><%= f.submit "Book Now!", class: "btn btn-primary btn-lg btn-block btn-booking" %></p>
  <% end %>
</div>

<% end %>

app/views/bookings/_pokemon_list.html.erb
<div class="container">
  <h3>Your Bookings</h3>
  <div class="card-container">
    <% @pokemon.bookings.each do |booking| %>
      <div class="card-product p-3">
        <div class="card-product-infos">
          <div class="row">
            <div class="col justify-around">
              <h2>
                Booking ID: <%= booking.id %>
                <% if (Time.now > booking.end_dt) %>
                  <span class="ml-3 mb-2 badge badge-pill badge-info">Booking complete!</span>
                <% else %>
                  <%= link_to '', booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:'fas fa-trash red' %>
                <% end %>
              </h2>
              <li><%= (booking.end_dt - booking.start_dt).to_i %> days</li>
              <li>Booking start: <%= booking.start_dt.to_formatted_s(:rfc822) %></li>
              <li>Booking ended: <%= booking.end_dt.to_formatted_s(:rfc822)   %></li>
              <%# else %>
                <!-- <img class= 'completed' src="https://res.cloudinary.com/deyw9z6tu/image/upload/c_scale,q_61,r_10,w_100/v1559055260/PokePoke/completed_nje2az.png"> -->
            </div>
            <div class="col justify-around text-right">
              <h2>Price: $<%= booking.price_paid %> </h2>

              <p>Renter: <%= User.find(booking.user.id).first_name %></p>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/_reviewcard.html.erb
<div class="card-product p-3">
  <img src="<%= pokemon.photo %>">
  <div class="card-product-infos">
    <div class="row">
      <div class="col-8 flex-column d-flex">
        <h2>
          <%= pokemon.name.titleize %>
        <small>
          <% if (review) %>
            <span class="stars badge badge-pill">
              <% review.rating.times do  %>
                <i class='fas fa-star'></i>
              <% end %>
              <% (5 - review.rating).times do  %>
                <i class='far fa-star'></i>
              <% end %>
            </span>
          <% end %>
          <% if (Time.now > booking.end_dt && !booking.review) %>
            <button type="button" data-toggle="collapse" data-target="#collapse<%= index + 1 %>" aria-expanded="false" aria-controls="collapse<%= index + 1 %>">Write Review</button>
          <% elsif (Time.now < booking.start_dt ) %>
            <span class="badge badge-pill badge-primary"> Upcoming!
            </span>
            <%= link_to '', booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:'fas fa-trash red' %>
          <% elsif (Time.now > booking.start_dt && Time.now < booking.end_dt) %>
            <span class="badge badge-pill badge-success">Ongoing!</span>
          <% end %>
        </small>
        </h2>

        <p>
          You rented this pokemon from
          <%= booking.start_dt.to_formatted_s(:rfc822) %>
        to <%= booking.end_dt.to_formatted_s(:rfc822) %> from owner <strong><%= User.find(pokemon.user.id).first_name %></strong>
        </p>
      </div>
      <div class="col-4 flex-row justify-between text-right">
        <h6>$<%= booking.price_paid.to_i %> </h6>
        <p>Booking ID: <%= booking.id %></p>

      </div>
    </div>
  </div>
</div>

app/views/bookings/_stars.html.erb
<span class="stars badge badge-pill">
  <% review.rating.times do  %>
    <i class='fas fa-star'></i>
  <% end %>
  <% (5 - review.rating).times do  %>
    <i class='far fa-star'></i>
  <% end %>
</span>

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="p-2 text-center" style="font-family: 'Press Start 2P', cursive;">Bookings</h1>
  <p class="text-center">Here are all your bookings <%= current_user.first_name %>. Don't forget to leave a review!</p>
  <div class="card-container" id="accordian">
    <% @bookings.each_with_index do |booking, index| %>
      <% pokemon = booking.pokemon %>
      <% review = booking.review %>
      <div class="card-product p-3">
        <img src="<%= pokemon.photo %>">
        <div class="card-product-infos">
          <div class="row">
            <div class="col-8 flex-column d-flex">
              <h2>
                <%= pokemon.name.titleize %>
              <small>
                <% if (review) %>
                  <span class="stars badge badge-pill">
                    <% review.rating.times do  %>
                      <i class='fas fa-star'></i>
                    <% end %>
                    <% (5 - review.rating).times do  %>
                      <i class='far fa-star'></i>
                    <% end %>
                  </span>
                <% end %>
                <% if (Time.now > booking.end_dt && !booking.review) %>
                  <span id="starspan"><button type="button" data-toggle="collapse" data-target="#collapse<%= index + 1 %>" aria-expanded="false" aria-controls="collapse<%= index + 1 %>">Write Review</button></span>
                <% elsif (Time.now < booking.start_dt ) %>
                  <span class="badge badge-pill badge-primary"> Upcoming!
                  </span>
                  <%= link_to '', booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:'fas fa-trash red' %>
                <% elsif (Time.now > booking.start_dt && Time.now < booking.end_dt) %>
                  <span class="badge badge-pill badge-success">Ongoing!</span>
                <% end %>
              </small>
              </h2>

              <p>
                You rented this pokemon from
                <%= booking.start_dt.to_formatted_s(:rfc822) %>
              to <%= booking.end_dt.to_formatted_s(:rfc822) %> from owner <strong><%= User.find(pokemon.user.id).first_name %></strong>
              </p>
            </div>
            <div class="col-4 flex-row justify-between text-right">
              <h6>$<%= booking.price_paid.to_i %> </h6>
              <p>Booking ID: <%= booking.id %></p>

            </div>
          </div>
        </div>
      </div>
      <div class="collapse" id="collapse<%= index + 1 %>" data-parent="#accordian">
        <div class="card card-body" id="new_review_<%= booking.id %>">
          <%= render 'reviews/form', booking: booking, review: @review %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>
       <li>

                <%= link_to "new review", booking_reviews_new_path %>

              </li>