config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get "pokemons/inventory", to: "pokemons#inventory", as: "inventory"
  patch "pokemons/:id/reactivate", to: "pokemons#reactivate", as: "reactivate"
  patch "pokemons/:id/deactivate", to: "pokemons#deactivate", as: "deactivate"
  resources :pokemons do
    resources :bookings, except: %i[edit update]
  end
  resources :bookings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
  end
end

app/views/shared/_alerts.html.erb
<% unless flash[:success].nil? %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= flash[:success] %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% unless flash[:warning].nil? %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><%= flash[:warning] %></span>
     <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% unless flash[:failure].nil? %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><%= flash[:failure] %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Modals -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="registerModalLabel">Register</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "devise/registrations/new", locals: { resource: User.new, resource_name: 'user' } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "devise/sessions/new", locals: { resource: User.new, resource_name: 'user' } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to pokemons_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/deyw9z6tu/image/upload/v1559012403/PokePoke/pokeball_j7dyz0.png" %>
    PokePoke
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user.is_owner == false %>
        <li class="nav-item active">
            <%= link_to "Become an owner", new_pokemon_path, class: "nav-link" %>
        </li>
        <% end %>
      <% if current_user.is_owner == true %>
        <li class="nav-item">
          <%= link_to "My Pokemon", inventory_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class='fas fa-user'></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to 'Account', edit_user_registration_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
  <% else %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <button type="button" class="btn" data-toggle="modal" data-target="#registerModal">
        Sign Up
        </button>
      </li>
      <li class="nav-item">
        <button type="button" class="btn" data-toggle="modal" data-target="#loginModal">
        Login
        </button>
      </li>
      <li class="nav-item dropdown">
        <!--<%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>-->
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
  <% end %>
</div>

app/views/shared/_pokemon_form.html.erb
<div class="container">
  <%= simple_form_for(@pokemon) do |f| %>
    <% if @pokemon.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @pokemon.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group pt-3 pb-4">

      <%= f.label :name, "Pokemon", class: "input-control" %> <br>
      <%= f.select :name, options_for_select(@names), class: "form-control select2" %>
      <br><br>

      <%= f.label :level, class: "input-control" %> <br>
      <%= f.text_field :level, class: "form-control"  %> <br>

      <%= f.label :address, class: "input-control" %> <br>
      <%= f.text_field :address, class: "form-control" %> <br><br>

      <%= f.label :price_per_day, class: "input-control" %> <br>
      <%= f.text_field :price_per_day, class: "form-control" %> <br>

      <%= f.submit "Submit Pokemon", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<!-- <select id="city-input" class="select2"></select> -->