config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get "pokemons/inventory", to: "pokemons#inventory", as: "inventory"
  patch "pokemons/:id/reactivate", to: "pokemons#reactivate", as: "reactivate"
  patch "pokemons/:id/deactivate", to: "pokemons#deactivate", as: "deactivate"
  resources :pokemons do
    resources :bookings, except: %i[edit update]
  end
  resources :bookings, only: [:index, :show, :destroy, :update] do
    resources :reviews, only: [:create]
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  include PgSearch
  # include AlgoliaSearch

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :name, :level, :category, :address, :price_per_day, presence: true
  validates :price_per_day, :rating, numericality: true


  pg_search_scope :search_by_name,
    against: [:name, :category, :level, :address],
    using: {
      tsearch: { prefix: true }
    }

  # algoliasearch do
  #   searchableAttributes ['name']

  #   attributesForFaceting ['searchable(price_per_day)', 'searchable(address)', 'searchable(rating)', :name]
  # end


  # TODO: Validate photos and ratings?

  def unavailable_dates
    bookings.pluck(:start_dt, :end_dt).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/pokemons_controller.rb
require 'open-uri'
require 'json'

class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_pokemon, only: [:show, :update, :edit, :deactivate, :reactivate]

  def index
    if params[:query].present?
      @pokemons = policy_scope(Pokemon).search_by_name(params[:query])
    else
      @pokemons = policy_scope(Pokemon)
    end

    @markers = @pokemons.map do |selected|
      pokemon_category = get_pokemon_category(selected.price_per_day)

      {
        lat: selected.latitude,
        lng: selected.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { selected: selected }),
        category: pokemon_category,
        flag: true
      }
    end
  end

  def inventory
    @user = current_user
    @pokemons = Pokemon.where(user: @user)
      .left_joins(:bookings)
      .group(:id)
      .order('COUNT(bookings.id) DESC')
    authorize @pokemons
  end

  def show
    @booking = Booking.new

    pokemon_category = get_pokemon_category(@pokemon.price_per_day)

    @markers = [{ lat: @pokemon.latitude, lng: @pokemon.longitude, category: pokemon_category }]
  end

  def new
    @pokemon = Pokemon.new
    @names = get_names
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    authorize @pokemon

    pokemon_info = get_pokemon_info(@pokemon.name.downcase)
    @pokemon.category = pokemon_info['types'][0]['type']['name']
    @pokemon.photo = pokemon_info['sprites']['front_default']

    if @pokemon.save
      @pokemon.user.is_owner = true
      @pokemon.user.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
  end

  def edit
    @names = get_names
  end

  def update
    if @pokemon.update(pokemon_params)
      redirect_to pokemon_path(@pokemon)
    else
      render :edit
    end
  end

  def deactivate
    @pokemon.is_active = false
    @pokemon.save
    flash[:success] = "#{@pokemon.name} is deactivated."
    redirect_to pokemon_path(@pokemon)
  end

  def reactivate
    @pokemon.is_active = true
    @pokemon.save
    flash[:success] = "#{@pokemon.name} is activated!"
    redirect_to pokemon_path(@pokemon)
  end

  private

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def pokemon_params
    params.require(:pokemon).permit(:name, :level, :price_per_day, :address)
  end

  def get_names
    names = []
    url = 'https://pokeapi.co/api/v2/pokemon?limit=20'
    json = open(url).read
    data = JSON.parse(json)['results']
    data.each do |result|
      names << result['name']
    end
    return names
  end

  def get_pokemon_info(name)
    url = "https://pokeapi.co/api/v2/pokemon/#{name}"
    # raise
    pokemon_serialized = open(url).read
    return JSON.parse(pokemon_serialized)
  end

  def get_pokemon_category(price_per_day)
    if price_per_day > 40
      return 'expensive'
    elsif price_per_day > 25
      return 'moderate'
    else
      return 'cheap'
    end
  end
end

app/views/pokemons/_infowindow.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <!-- <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol> -->
  <div class="carousel-inner">
    <div class="carousel-item active">

      <div class="container mt-3">
        <div>
          <h3><%= selected.name.titleize %></h3>
          <strong>Category: </strong><%= selected.category %> |
          <strong>Level: </strong><%= selected.level %> |
          <strong>Address: </strong><%= selected.address %> |
          <strong>Rating: </strong><%= selected.rating %> |
          <strong>Price per day: </strong><%= selected.price_per_day %> <br>
        </div>
        <div>
          <p><%= link_to 'Book now', pokemon_path(selected), class: "btn btn-success" %></p>
        </div>
      </div>

    </div>

    <div class="carousel-item">
        <img id="info-pic" src="<%= selected.photo %>">
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pokemons/_reviews.html.erb
<div class="container">


  <h3><%= @pokemon.name.titleize %>'s Reviews</h3>

  <div class="card-container">
    <% @pokemon.reviews.each do |review| %>
      <div class="card-product p-3">
        <div class="card-product-infos">
          <div class="row">
            <div class="col justify-around">

              <h2>
                Booking ID: <%= review.booking_id %>
              </h2>
              <p><% if (review) %>
                  <span class="stars badge badge-pill">
                    <% review.rating.times do  %>
                      <i class='fas fa-star'></i>
                    <% end %>
                    <% (5 - review.rating).times do  %>
                      <i class='far fa-star'></i>
                    <% end %>
                  </span>
                <% end %> by anonymous</p>
                <p><%= review.content %></p>


            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/edit.html.erb
<%= render 'shared/pokemon_form' %>

app/views/pokemons/index.html.erb
<div class="container">
  <h1 class="p-2 text-center" style="font-family: 'Press Start 2P', cursive;">PokePoke</h1>
  <h6 class="p-2 text-center">A wild Squirtle appeared! Matey, you're walking the plank if you lose! My function is to provide Ash with information and advice regarding Pokémon and their training. If lost or stolen, I cannot be replaced. If I had started as a trainer at your age... </h6>
  <form>
    <%= form_tag pokemons_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control my-3 float-left",
        placeholder: "Find a pokemon"
      %>
    <% end %>
  </form>

  <div
    mapindex="<%= @mapindex %>"
    id="map"
    style="width: 100%;
    height: 350px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>

  <div class="card-container">
    <% @pokemons.each do |pokemon| %>
      <%= link_to pokemon_path(pokemon) do  %>
        <div class="card-product">
          <img src="<%= pokemon.photo %>">
          <div class="card-product-infos">
            <div class="row">
              <div class="col-6 justify-around">
                <h2><%= pokemon.name.titleize %></h2>
                <p>This pokemon is a <strong><%= pokemon.category %></strong> type.</p>
                <p>Level <%= pokemon.level %></p>
              </div>
              <div class="col-6 justify-around text-right">
                <h2>$<%= pokemon.price_per_day %> per day</h2>
                <p>Rating: <%= pokemon.rating %></p>
                <p>Owner: <%= pokemon.user.first_name %></p>

              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
   </div>
</div>

app/views/pokemons/inventory.html.erb
<div class="container">
    <h1 class="p-2 text-center" style="font-family: 'Press Start 2P', cursive;"><%= current_user.first_name %>'s Pokemon</h1>
    <p>A wild Bulbasaur appeared! Meowth, that's right! Sometimes, you can find stuff on the ground! To unite all peoples within our nation. The early bird gets the worm, or in this case the Pokemon. My Pa said there are 100 kinds of Pokemon. I think there are more. I came down here to show off to girls.</p>
  <%= link_to "Add new Pokemon", new_pokemon_path, class: "btn btn-primary m-2" %>
  <div class="card-container" id="target">
    <% @pokemons.each_with_index do |pokemon, index| %>
      <div class="card-product" data-toggle="collapse" data-parent="#target" href="#collapse<%= index + 1 %>">
        <%= link_to pokemon_path(pokemon) do  %>
        <img src="<%= pokemon.photo %>">
         <% end %>
        <div class="card-product-infos">
          <div class="row">
            <div class="col-6 justify-around">
              <h2>
                <%= pokemon.name.titleize %>
                <% active = 0 %>
                <% past = 0 %>
                <% pokemon.bookings.each do |b| %>
                  <% if b.end_dt > Time.now %>
                    <% active += 1 %>
                  <% else %>
                    <% past += 1 %>
                  <% end %>
                <% end %>
                <span class="badge badge-pill badge-success"><%= active unless active == 0 %></span>
                <span class="badge badge-pill badge-info"><%= past unless past == 0 %></span>
                <span class="stars float-right">
              </h2>
              <p>This pokemon is a <strong><%= pokemon.category %></strong> type.</p>
              <p>Level <%= pokemon.level %></p>
            </div>
            <div class="col-6 justify-around text-right">
              <h2>
                <% sum = 0 %>
                <% pokemon.bookings.each do |b| %>
                  <% sum += b.price_paid.to_i %>
                  <% end %>
                  Income: $<%= sum %>
              </h2>


              <p>Rating: <%= pokemon.rating %></p>
       
            </div>
          </div>
        </div>
      </div>
      <% if pokemon.bookings.length > 0 %>
    <div id="collapse<%= index+1 %>" class="panel-collapse collapse">
      <div class="container">
        <div class="card-container">
          <% pokemon.bookings.each do |booking| %>
            <div class="card-product p-3">
              <div class="card-product-infos">
                <div class="row">
                  <div class="col justify-between">
                    <h2>
                      Booking ID: <%= booking.id %>
                      <small> - Renter: <%= User.find(booking.user.id).first_name %></small>
                      <% if (Time.now > booking.end_dt) %>
                        <span></span>
                      <% elsif %>
                        <%= link_to '', booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:'fas fa-trash red' %>
                      <% end %>
                    </h2>
                    <li><%= booking.start_dt.to_formatted_s(:rfc822) %> to <%= booking.end_dt.to_formatted_s(:rfc822)   %></li>
                    <%# else %>
                      <!-- <img class= 'completed' src="https://res.cloudinary.com/deyw9z6tu/image/upload/c_scale,q_61,r_10,w_100/v1559055260/PokePoke/completed_nje2az.png"> -->
                  </div>
                  <div class="col justify-around text-right">
                    <h2>Total: $<%= booking.price_paid %> </h2>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/pokemons/new.html.erb
<%= render 'shared/pokemon_form' %>

app/views/pokemons/show.html.erb
<div class="container">
  <h1 class="p-2">&nbsp;<%= @pokemon.name.titleize %>

  <% if policy(@pokemon).edit? %>
    <small>
      <%= link_to edit_pokemon_path(@pokemon) do %>
        <i class="fa fa-pencil-alt"></i>
      <% end %>
      <% if @pokemon.is_active %>
        <%= link_to deactivate_path(@pokemon), method: :patch do %>
          <i class="fas fa-circle" style="color: green;"></i>
        <% end %>
      <% else %>
        <%= link_to reactivate_path(@pokemon), method: :patch do %>
          <i class="fas fa-circle" style="color: red;"></i>
        <% end %>
      <% end %>
    </small>
  <% end %>

  </h1>
  <hr>

  <div class="card-show">
    <div class="top-card d-flex">
      <div class="image">
           <%= image_tag @pokemon.photo, width: 200, crop: :scale %>
      </div>
        <div class="show-map"
          id="map"
          style="width: 100%;
          height: 350px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
    </div>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <div class="list">

            <p><strong>Pokemon details</strong></p>
              <li>Type: <%= @pokemon.category.titleize %></li>
              <li>Level: <%= @pokemon.level %></li>
              <li>City: <%= @pokemon.address.titleize %></li>
              <li>Rating: <%= @pokemon.rating %></li>
              <li>Price: $<%= @pokemon.price_per_day.to_i %> a day</li>
              <br>

          </div>
        </div>
        <div class="col-8">
          <% if policy(@pokemon).edit? %>

            <%= render "reviews" %>

          <% else %>
            <%= render "bookings/new" %>
          <% end %>
        </div>

      </div>

    </div>
  </div>
</div>